sudo: required
language: python
services:
  - docker
addons:
  apt:
    packages:
      # Update docker to be able to use working dir in exec commands
      - docker-ce
before_install:
  - cd docker
  - export REPO=eczech/celldom # Set docker hub repo name (TODO: get permissions for hammerlab dockerhub)
  - export TAG="$REPO:$(if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi)"
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - docker build --build-arg TF_IMAGE=tensorflow/tensorflow:1.7.0-py3 --build-arg CELLDOM_REPO_BRANCH=$BRANCH -t $TAG -f Dockerfile.prd .
  - docker run -d --rm --name celldom $TAG
  - docker ps -a
  #  CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                NAMES
  #  0682f850c3de        celldom             "/bin/sh -c 'jupyter…"   27 seconds ago      Up 24 seconds       6006/tcp, 8888/tcp   celldom
  - cd ..
script:
  - docker exec celldom pip install nose coveralls pylint
  - docker exec -w /lab/repos/celldom/python/source celldom nosetests --exe -sv tests/ --with-coverage --cover-inclusive --cover-package=celldom
  - docker exec -w /lab/repos/celldom/python/source celldom bash ./.lint.sh
after_success:
  - docker cp celldom:/lab/repos/celldom/python/source/.coverage .
  - sed -i 's|/lab/repos/celldom/||g' .coverage
  - coveralls
before_deploy:
  - echo "Docker user = $DOCKER_USERNAME"
  - echo "$DOCKER_PASSWORD" | docker login --username eczech --password-stdin
deploy:
  provider: script
  script: docker push $TAG
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(r[0-9]{1,3}[.][0-9]{1,3}|master)$