sudo: required
language: python
services:
  - docker
before_install:
  - cd docker
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - docker build --build-arg TF_IMAGE=tensorflow/tensorflow:1.7.0-py3 --build-arg CELLDOM_REPO_BRANCH=$BRANCH -t celldom -f Dockerfile.prd .
  - docker run -d --name app flask-demo-app
  - docker ps -a
script:
  - docker exec app python -m unittest discover
script:
  - nosetests --exe -sv tests/ --with-coverage --cover-inclusive --cover-package=cytokit
  - bash ./.lint.sh
after_success:
  - coveralls
before_deploy:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
deploy:
  provider: script
  script: docker push eczech/celldom
  on:
    branch: master