apt_margins: {bottom: 45, left: -156, right: 49, top: -179}
apt_num_digit_bounds:
- {bottom: 26, left: 0, right: 22, top: 0}
- {bottom: 26, left: 13, right: 38, top: 0}
- {bottom: 26, left: 29, right: 51, top: 0}
apt_num_digit_count: 3
apt_num_margins: {bottom: -101, left: -8, right: 43, top: -127}
apt_num_range: [0, 46]
apt_num_rotation: 0
components:
  chamber:
    boundary:
    - [81, 8]
    - [128, 9]
    - [145, 35]
    - [148, 106]
    - [143, 173]
    - [124, 205]
    - [105, 221]
    - [98, 221]
    - [68, 188]
    - [58, 160]
    - [61, 46]
    - [70, 21]
  trap:
    boundary:
    - [57, 196]
    - [151, 196]
    - [151, 255]
    - [57, 255]
marker_spacing: {horizontal: 208, vertical: 218}
name: ML01
st_num_digit_bounds:
- {bottom: 26, left: 0, right: 22, top: 0}
- {bottom: 26, left: 14, right: 39, top: 0}
- {bottom: 26, left: 31, right: 53, top: 0}
st_num_digit_count: 3
st_num_margins: {bottom: -4, left: -149, right: -96, top: -30}
st_num_range: [0, 127]
st_num_rotation: 0
