apt_margins: {bottom: 15, left: -92, right: 93, top: -178}
apt_num_digit_bounds:
- {bottom: 35, left: 0, right: 27, top: 15}
- {bottom: 21, left: 0, right: 27, top: 0}
apt_num_digit_count: 2
apt_num_margins: {bottom: -11, left: 56, right: 83, top: -46}
apt_num_range: [0, 46]
apt_num_rotation: -90
components:
  chamber:
    boundary:
    - [93, 16]
    - [80, 17]
    - [69, 19]
    - [58, 24]
    - [46, 32]
    - [36, 41]
    - [28, 52]
    - [22, 64]
    - [19, 75]
    - [18, 88]
    - [19, 100]
    - [22, 116]
    - [27, 125]
    - [35, 137]
    - [44, 147]
    - [54, 154]
    - [68, 160]
    - [76, 162]
    - [84, 171]
    - [92, 181]
    - [101, 170]
    - [107, 162]
    - [131, 153]
    - [139, 147]
    - [149, 137]
    - [158, 124]
    - [164, 109]
    - [166, 98]
    - [166, 88]
    - [165, 75]
    - [161, 64]
    - [155, 51]
    - [148, 41]
    - [139, 32]
    - [128, 25]
    - [116, 19]
    - [107, 17]
    - [93, 16]
marker_spacing: {horizontal: 198, vertical: 198}
name: G01
st_num_digit_bounds:
- {bottom: 35, left: 0, right: 27, top: 15}
- {bottom: 21, left: 0, right: 27, top: 0}
st_num_digit_count: 2
st_num_margins: {bottom: -11, left: -83, right: -56, top: -46}
st_num_range: [0, 31]
st_num_rotation: -90

