name: Chip 1
target_scale_factor: 254.16
apt_margins:
    left: -160
    right: 75
    bottom: 60
    top: -250
apt_num_margins:
  left: 0
  right: 75
  bottom: -175
  top: -205
apt_num_digit_count: 3
apt_num_digit_bounds: [[3, 28], [22, 48], [42, 68]]
st_num_margins:
  left: -150
  right: -65
  bottom: -5
  top: -37
st_num_digit_count: 3
st_num_digit_bounds: [[3, 28], [22, 48], [42, 68]]