apt_margins: {bottom: 14, left: -92, right: 93, top: -179}
apt_num_digit_bounds:
- {bottom: 35, left: 0, right: 25, top: 15}
- {bottom: 21, left: 0, right: 25, top: 0}
apt_num_digit_count: 2
apt_num_margins: {bottom: -12, left: 57, right: 82, top: -47}
apt_num_range: [0, 100]
apt_num_rotation: -90
components:
  chamber:
    boundary:
    - [92, 15]
    - [79, 16]
    - [68, 19]
    - [58, 24]
    - [46, 31]
    - [35, 40]
    - [28, 52]
    - [22, 64]
    - [19, 75]
    - [18, 88]
    - [19, 100]
    - [22, 116]
    - [27, 125]
    - [35, 137]
    - [44, 147]
    - [54, 154]
    - [68, 160]
    - [76, 162]
    - [84, 171]
    - [92, 180]
    - [101, 170]
    - [107, 162]
    - [131, 153]
    - [139, 147]
    - [149, 137]
    - [158, 124]
    - [164, 109]
    - [166, 98]
    - [166, 88]
    - [165, 75]
    - [161, 64]
    - [155, 51]
    - [148, 41]
    - [139, 32]
    - [128, 25]
    - [116, 19]
    - [107, 16]
    - [99, 15]
marker_spacing: {horizontal: 198, vertical: 198}
name: G01
st_num_digit_bounds:
- {bottom: 33, left: 0, right: 25, top: 14}
- {bottom: 20, left: 0, right: 25, top: 0}
st_num_digit_count: 2
st_num_margins: {bottom: -13, left: -82, right: -57, top: -46}
st_num_range: [0, 100]
st_num_rotation: -90

