apt_bbox: {bottom: 307, left: 12, right: 224, top: 11}
apt_margins: {bottom: 56, left: -148, right: 64, top: -240}
apt_num_digit_bounds:
- {bottom: 31, left: 0, right: 21, top: 0}
- {bottom: 31, left: 15, right: 41, top: 0}
- {bottom: 31, left: 35, right: 57, top: 0}
apt_num_digit_count: 3
apt_num_margins: {bottom: -174, left: 6, right: 63, top: -205}
apt_num_range: [0, 46]
apt_num_rotation: 0
components:
  chamber:
    boundary:
    - [82, 7]
    - [128, 7]
    - [137, 18]
    - [144, 34]
    - [149, 52]
    - [148, 196]
    - [144, 211]
    - [136, 228]
    - [105, 260]
    - [77, 232]
    - [66, 211]
    - [61, 191]
    - [61, 50]
    - [68, 27]
    - [75, 15]
  trap:
    boundary:
    - [64, 261]
    - [146, 261]
    - [146, 295]
    - [64, 295]
marker_spacing: {horizontal: 255, vertical: 275}
name: G02
st_num_digit_bounds:
- {bottom: 31, left: 0, right: 22, top: 0}
- {bottom: 31, left: 17, right: 43, top: 0}
- {bottom: 31, left: 37, right: 58, top: 0}
st_num_digit_count: 3
st_num_margins: {bottom: -7, left: -145, right: -87, top: -38}
st_num_range: [0, 31]
st_num_rotation: 0
template_image_path: /lab/repos/celldom/config/chip/chip-G02/chip-G02.png

