name: Experiment "exp-20180217-G1-K562-control-01" Analysis
measurement_inference:
  min_measurement_gap_seconds: 3600
apartment_classification:
  cell_class: {type: any, component: chamber}
apartment_summary:
  cell_class: {type: any, component: chamber}
  # Use no initial conditions for growth rate calculations
  initial_condition: []
confluence_detection:
  component: chamber
  threshold: .5