CLASS_NAME_MARKER = 'Marker'
CLASS_NAME_CELL = 'Cell'

ACQ_TYPE_BF = 'bf-object'
ACQ_TYPE_BFFL = 'bf-object+fl-expression'
ACQ_TYPE_FL = 'fl-object+fl-expression'
ACQ_TYPES = [ACQ_TYPE_BF, ACQ_TYPE_BFFL, ACQ_TYPE_FL]
ACQ_TYPES_MULTI_CHANNEL = [ACQ_TYPE_BFFL, ACQ_TYPE_FL]

ACQ_CH_CONTENT_CELL = 'cell'
ACQ_CH_CONTENT_EXPR = 'expression'
ACQ_CH_CONTENTS = [ACQ_CH_CONTENT_CELL, ACQ_CH_CONTENT_EXPR]

ACQ_CH_TYPE_BF = 'brightfield'
ACQ_CH_TYPE_FL = 'fluorescent'
ACQ_CH_TYPES = [ACQ_CH_TYPE_BF, ACQ_CH_TYPE_FL]
